@startuml
title Initialisation of Client Tool
actor User
User -> Client : Opens first time
User -> Client : (Selects database to use)
Client -> Server: getAvailableCampaigns() : Campaigns[]
Client -> Client: selectFirstCampaign() : void
Client -> Server: getAvailableParameters(Campaign) : Parameters[]
Client -> Client: updateTimeAndGeoBounds() : void

User -> Client : Clicks on refresh
Client -> User: No parameter selected yet
User -> Client : Selects parameter
User -> Client : Clicks on refresh

Client -> Server: getObservations(RequestParams) : Result

@enduml