/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_esa_s2tbx_jni_EnvironmentVariablesNative */

#ifndef _Included_org_esa_s2tbx_jni_EnvironmentVariablesNative
#define _Included_org_esa_s2tbx_jni_EnvironmentVariablesNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_esa_s2tbx_jni_EnvironmentVariablesNative
 * Method:    chdir
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_esa_s2tbx_jni_EnvironmentVariablesNative_chdir
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_esa_s2tbx_jni_EnvironmentVariablesNative
 * Method:    getcwd
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_esa_s2tbx_jni_EnvironmentVariablesNative_getcwd
  (JNIEnv *, jclass);

/*
 * Class:     org_esa_s2tbx_jni_EnvironmentVariablesNative
 * Method:    getenv
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_esa_s2tbx_jni_EnvironmentVariablesNative_getenv
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_esa_s2tbx_jni_EnvironmentVariablesNative
 * Method:    putenv
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_esa_s2tbx_jni_EnvironmentVariablesNative_putenv
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
